image_size="Standard_F2"
public_ip_name="spring_public"
agent_vm_name="azure_tf_vm"
admin_username="srinu"
admin_password="srinu1234aA@"
network_interface_name="spring_network_interface"
custom_ss_key_pem="aks_pem_key"
network_security_group="security_group"